services:

    kicker.analyzer:
        class: InfoGoal\ApiBundle\Service\DataAnalyzer
        arguments: [@doctrine.orm.entity_manager, @kicker.calculator, @kicker.achievements]

    kicker.api:
        class: InfoGoal\ApiBundle\Service\Api
        arguments: [@kicker.analyzer]

    kicker.calculator:
        class: InfoGoal\ApiBundle\Service\ExpCalculator
        arguments: [@doctrine.orm.entity_manager]

    kicker.achievements:
        class: InfoGoal\ApiBundle\Service\Achievements
        arguments: [@doctrine.orm.entity_manager]

    kicker.rezervation:
        class: InfoGoal\KickerBundle\Service\Reservation
        arguments: [@doctrine.orm.entity_manager]