<?php

namespace InfoGoal\KickerBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PlayersBadgesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlayersBadgesRepository extends EntityRepository
{
}
