<?php

namespace InfoGoal\KickerBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TableOptionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TableOptionRepository extends EntityRepository
{

}
