info_goal_kicker_homepage:
    path:     /
    defaults: { _controller: InfoGoalKickerBundle:Table:index }

profile_index:
    path:     /profile
    defaults: { _controller: InfoGoalKickerBundle:Profile:index }

profile_page:
    path:     /profile/{id}
    defaults: { _controller: InfoGoalKickerBundle:Profile:index }

reserved_index:
    path:     /reserved
    defaults: { _controller: InfoGoalKickerBundle:Table:reservation }

info_goal_kicker_users_index:
    path:     /users
    defaults: { _controller: InfoGoalKickerBundle:Users:index }

info_goal_kicker_users:
    path:     /users/{page}
    defaults: { _controller: InfoGoalKickerBundle:Users:index }

info_goal_kicker_timeline_index:
    path:     /timeline
    defaults: { _controller: InfoGoalKickerBundle:Timeline:index }

info_goal_kicker_timeline:
    path:     /timeline/{page}
    defaults:  { _controller: InfoGoalKickerBundle:Timeline:index }

info_goal_kicker_badges_index:
    path:     /badges
    defaults: { _controller: InfoGoalKickerBundle:Badges:index }