info_goal_kicker_homepage:
    path:     /
    defaults: { _controller: InfoGoalKickerBundle:Table:index }

profile_index:
    path:     /profile
    defaults: { _controller: InfoGoalKickerBundle:Profile:index }

api_index:
    path:     /api
    defaults: { _controller: InfoGoalKickerBundle:Api:index}

