services:
    kicker.api:
        class: InfoGoal\KickerBundle\Service\Api

    #kicker.analyzer:
    #     class: InfoGoal\KickerBundle\Service\DataAnalyzer
    #     calls:
    #         - [setEntityManager, [@doctrine.orm.entity_manager]]