InfoGoal\KickerBundle\Entity\Game:
    type: entity
    table: games
    repositoryClass: InfoGoal\KickerBundle\Entity\GameRepository
    manyToOne:
            player1:
                targetEntity: Player
                inversedBy: games1
                joinColumn:
                    name: player_1
                    referencedColumnName: id
            player2:
                targetEntity: Player
                inversedBy: games2
                joinColumn:
                    name: player_2
                    referencedColumnName: id
            player3:
                targetEntity: Player
                inversedBy: games3
                joinColumn:
                    name: player_3
                    referencedColumnName: id
            player4:
                targetEntity: Player
                inversedBy: games4
                joinColumn:
                    name: player_4
                    referencedColumnName: id
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        dateStart:
            type: datetime
            column: date_start
        dateEnd:
            type: datetime
            column: date_end
            nullable: TRUE
        goal1:
            type: smallint
            column: goal_1
            nullable: TRUE
        goal2:
            type: smallint
            column: goal_2
            nullable: TRUE
    lifecycleCallbacks: {  }
