InfoGoal\KickerBundle\Entity\Game:
    type: entity
    table: games
    repositoryClass: InfoGoal\KickerBundle\Entity\GameRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        dateStart:
            type: datetime
            column: date_start
        dateEnd:
            type: datetime
            column: date_end
        player1:
            type: integer
            column: player_1
        player2:
            type: integer
            column: player_2
        player3:
            type: integer
            column: player_3
        player4:
            type: integer
            column: player_4
        goal1:
            type: smallint
            column: goal_1
        goal2:
            type: smallint
            column: goal_2
    lifecycleCallbacks: {  }
