InfoGoal\KickerBundle\Entity\PlayersBadges:
    type: entity
    table: null
    repositoryClass: InfoGoal\KickerBundle\Entity\PlayersBadgesRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        date:
            type: datetime
    manyToOne:
        badges:
            targetEntity: Badge
            inversedBy: BP
            joinColumn:
                name: badgeId
                referencedColumnName: id
        players:
            targetEntity: Player
            inversedBy: PB
            joinColumn:
                name: playerId
                referenceColumnName: id
    lifecycleCallbacks: {  }


