InfoGoal\KickerBundle\Entity\Player:
    type: entity
    table: players
    repositoryClass: InfoGoal\KickerBundle\Entity\PlayerRepository
    oneToMany:
            games1:
                targetEntity: Game
                mappedBy: player1
            games2:
                targetEntity: Game
                mappedBy: player2
            games3:
                targetEntity: Game
                mappedBy: player3
            games4:
                targetEntity: Game
                mappedBy: player4
            PB:
                targetEntity: PlayersBadges
                mappedBy: players
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        cardId:
            column: cardId
            type: integer
            length: 10
        name:
            column: name
            type: string
            length: 50
        xp:
            column: xp
            type: integer
        levelXp:
            column: levelXp
            type: integer
        level:
            column: level
            type: integer
        played:
            column: played
            type: integer
        won:
            column: won
            type: integer
        lastGame:
            column: lastGame
            type: datetime
            nullable: TRUE
        photo:
            column: photo
            type: string
            length: 100
    lifecycleCallbacks: {  }